_github-challenge-HtetCorporation-organization_github-challenge-HtetCorporation-organization.domains.google
1. Create a TXT record in your DNS configuration for the following hostname: _github-challenge-HtetCorporation-organization.domains.google
2. Use this code for the value of the TXT record: bfd11156bd. Please note that the code will expire in 7 days.
3. Wait until your DNS configuration changes. This could take up to 72 hours to propagate.

1. Create a TXT record in your DNS configuration for the following hostname: _github-challenge-HtetCorporation-organization.domains.google
2. Use this code for the value of the TXT record: bfd11156bd. Please note that the code will expire in 7 days.
3. Wait until your DNS configuration changes. This could take up to 72 hours to propagate.
_github-challenge-HtetCorporation-organization.domains.google
